### ISSUE TITLE
ScrollX not working properly over shape()

### ISSUE THREAD

**Issue by rfpuyana** [ojack/hydra#100]
When attempting to scroll a shape(),  position is shifted but animated scrolling is not performed.
scrollX() works ok with other types of outputs.

Try: shape().scrollX(1,1).out()

**Comment by zachkrall** [comment]
scrollX(1) should almost be a like full return to it's original position, but it looks like the texture doesn't wrap the same way it use to

<img width="1262" alt="Screen Shot 2020-08-10 at 12 34 24 PM" src="https://user-images.githubusercontent.com/2532937/89807161-3002d480-db06-11ea-98fe-66d728bd71e9.png">

**Comment by rfpuyana** [comment]
Yeah, if you do the scrolling in o1 it works

shape().out(o0)

src(o0).scrollX(1,1).out(o1)

render(o1)

**Comment by zachkrall** [comment]
yeah that's really odd. this is like happening inside of [hydra-synth](https://github.com/ojack/hydra-synth) tho

**Comment by micuat** [comment]
related to https://github.com/ojack/hydra-synth/issues/62 ? but it seems fixed in the current version (1.3.4)

**Comment by ojack** [comment]
Closing because I believe this has been fixed for a while.
