### ISSUE TITLE
Is there a way to prevent cntrl + left-arrow to go back to the previous route in history?

### ISSUE THREAD

**Issue by Kraloz** [ojack/hydra#107]
I use that shortcut to jump beweeen words while I code, how can I prevent this behaviour? Is there a whay to unbind the key?

**Comment by Kraloz** [comment]
I ended up writing a simple script for tampermonkey that overrides `window.history.forward` and `window.history.back` functions

```
// ==UserScript==
// @name         Disable Hydra cntrol + left/right arrow shortcut
// @namespace    http://tampermonkey.net/
// @version      0.1
// @author       Kraloz
// @match        https://hydra.ojack.xyz/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    window.history.back = () => {}
    history.forward = () => {}
})();
```

Anyways, I think that cntrl + left/right it's a common shorcut in programming enviroments

**Comment by zackkrida** [comment]
i have this habit too and always lose my work in hydra. great script 👍

**Comment by Kraloz** [comment]
Hey, Thanks! This is my first time 'contributing' to something in the oss community. I'm glad that it helped you

**Comment by ojack** [comment]
Hey @Kraloz  thanks for this! and congrats on your first contribution!!!
Maybe I should change the binding for back and forward in saved sketches...I didn't realize it was interfering with such a common use case.

**Comment by cediorio** [comment]
I also have this issue! And thanks, Kraloz, your script works a charm.

**Comment by mtdrewski** [comment]
Thank you! I also had this issue since operation ctrl+left got into my muscle memory

**Comment by ojack** [comment]
This should be fixed now! The history forward and back has been changed to "ctrl+shift+left" and "ctrl+shift+right", and the regular control arrows should have default behavior.

Please let me know if everything is working :)
