### ISSUE TITLE
p5.hide does not work properly under transparent textures

### ISSUE THREAD

**Issue by micuat** [ojack/hydra#110]
https://github.com/ojack/hydra/blob/master/hydra-server/app/src/p5-wrapper.js#L34

currently it's pushing the canvas to the back but it is still visible under transparent textures (e.g., `solid(0,0,0,0)`. something like visibility hidden would be better? I will check the code later

**Comment by ojack** [comment]
oooh yes, I think visibility hidden would be much better!

**Comment by micuat** [comment]
@ojack should I edit based on the main branch and make another branch for PR? (it seems dev branch is not up to date)
