### ISSUE TITLE
use github actions for build and exclude bundles

### ISSUE THREAD

**Issue by micuat** [ojack/hydra#126]
potentially we can use github actions for automated build and exclude bundle.js files:
https://docs.github.com/en/actions/guides/building-and-testing-nodejs

**Comment by ojack** [comment]
Ohh this is a great idea! I haven't used this before. I think the one thing
is that I would still like to make sure the bundled version is included
when you download the repo.... just because many people like to download
and run locally without understanding all of the build steps.

**Comment by micuat** [comment]
I think you can point the default repo to the build result. I will check if I can set it up on my fork.

**Comment by micuat** [comment]
here's an example of action https://github.com/micuat/hydra/blob/actiontest/.github/workflows/node.js.yml

the repo with bundled files can be downloaded here https://github.com/micuat/hydra/actions/runs/734610316
(not sure if it's possible to make a permanent link for download)

**Comment by micuat** [comment]
In the end I think it's not worth using github actions because I think anyways users need to `npm i` when they download the repo, so why not doing `npm run build-main` as well. I don't know what is the best practice in this case but we can stick to having the bundle included and/or making a separate doc for deploying hydra on local server

**Comment by ojack** [comment]
Okay thank you for investigating this! I really go back and forth....I was
thinking that some people use this without having node installed, but i
just realized that that isn't possible as node is required to run the
server anyway..... this makes me lean towards not including bundle. I
definitely want to improve the build process as the current way of
switching between bundle and bundle.min is terrible :)
