### ISSUE TITLE
question about p5.sound.js

### ISSUE THREAD

**Issue by rekombination** [ojack/hydra#134]
first of all, thank you for the great work!

i've a question rather than a issue. is it possible to use the p5.sound.js library inside hydra?
i've seen that the library is already included in the node modules. 
i also played a bit with the p5 integration which worked for me.. 
(thanks for the [example](https://raw.githubusercontent.com/ojack/hydra-examples/master/6-p5.js))
however i couldn't find a way to use the p5.sound library.

if it should be possible how would this [example](https://p5js.org/reference/#/p5.AudioIn) look like to use it in hydra?

```
let mic;

 function setup(){
  let cnv = createCanvas(windowWidth, windowHeight);
  cnv.mousePressed(userStartAudio);
  textAlign(CENTER);
  mic = new p5.AudioIn();
  mic.start();
}

function draw(){
  background(0);
  fill(255);
  text('tap to start', width/2, 20);

  micLevel = mic.getLevel();
  let y = height - micLevel * height;
  ellipse(width/2, y, 100, 100);
}
```

it would be great if someone could give me a hint.

**Comment by ojack** [comment]
loadScript is now added --- check the readme for details
