### ISSUE TITLE
Remove link to forum on website

### ISSUE THREAD

**Issue by hellocatfood** [ojack/hydra#143]
The welcome message on the website features a link to https://talk.lurk.org/channel/hydra which no longer exists. Can it be removed?

**Comment by ritchse** [comment]
Moreover, let's replace it with an invite to the discord

**Comment by ojack** [comment]
Forum link now removed :) !
https://github.com/ojack/hydra/commit/28b2e6a0829f47211492fff1e1f5aab405c120fb

@ritchse there already is a discord link? or do you want to add it somewhere else as well?
