### ISSUE TITLE
Shorcut CTRL+LEFT or CTRL+RIGHT is causing a lot of problems.

### ISSUE THREAD

**Issue by Rafrobeat** [ojack/hydra#144]
Hi! The shorcut is CTRL + LEFT or CTRL + RIGHT is causing a lot of problems with Hydra web. People who come from writing or programming use these shorcuts a lot to move through the words or lines of the text or code, also to select the code, but in Hydra it is happening that a kind of back / forward of the Skecth is activated. and it is very confusing because the code that is being written is lost. Is it possible to remap these shorcuts?

Thank you!

**Comment by gtnbssn** [comment]
There's a solution with tampermonkey there: https://github.com/ojack/hydra/issues/107

**Comment by ojack** [comment]
This should now be working! please confirm :)

**Comment by Rafrobeat** [comment]
Thank you @ojack ! all fine!
