### ISSUE TITLE
Flash highlight text on code execution

### ISSUE THREAD

**Issue by ojack** [ojack/hydra#16]
Like https://github.com/tidalcycles/atom-tidalcycles/blob/97dfbb4b228d2dd3588bc296ca6bd7c0f4cf4418/lib/repl.js#L231

**Comment by hektormisplon** [comment]
Is it possible that the eval block is not showing the highlight? I only tested in Firefox, but it seems like the event should trigger the `getCurrentBlock` function to get the highlight.
