### ISSUE TITLE
As a user, I want to execute Hydra code from a mobile browser. 

### ISSUE THREAD

**Issue by rfpuyana** [ojack/hydra#21]
Although Hydra works in mobile browsers, the lack of the cmd/ctrl key makes it imposible to execute the code. An alternative could be displaying a [RUN CODE] button that shows up only in mobile browsers.

**Comment by ojack** [comment]
i like this idea! open to a pull request if you want to try it out!

**Comment by TrueFiasco** [comment]
So 1 year on what’s happened with this request?

**Comment by ojack** [comment]
This exists!
