### ISSUE TITLE
Using webcam on Windows crashes regl

### ISSUE THREAD

**Issue by echophon** [ojack/hydra#24]
Hi! 

When I try to run the webcam example on the latest build at: https://hydra-editor-v1.glitch.me 

ie
s0.initCam() 
src(s0).out() 

The output loads for a few seconds and crashes to a black screen a few moments later.  The console then starts loading the following error over & over.

regl.js:47 Uncaught Error: (regl) context lost
    at Function.raise (regl.js:47)
    at Object.REGLCommand [as draw] (regl.js:9396)
    at passes.forEach (output.js:196)
    at Array.forEach (<anonymous>)
    at Output.tick (output.js:196)
    at HydraSynth.tick (index.js:293)
    at Engine.<anonymous> (index.js:52)
    at emitOne (events.js:106)
    at Engine.emit (events.js:184)
    at Engine.tick (index.js:42)

Initial Test - Reproduced on Win10 desktop, Chrome 68, GTX1070, dual 2560x1440 144Hz resolution monitors (one rotated to portrait) and this model of webcam https://www.amazon.com/ELP-2-8-12mm-Varifocal-1-3megapixel-Android/dp/B01N8YH5VY  

The error can be cleared by refreshing but fails again a few seconds after initCam()

Test 2 - cannot repro with same webcam attached to older MBP with Nvidia card.  also on Chrome 68.  This should rule out the camera as cause.
 
Test 3 - 144Hz is only supported over displayport, & one of my screens is connected via HDMI and runs instead at 60Hz.  Unable to repro on the screen that runs at 60Hz.  So it appears that it is the increased frequency at 144Hz that is the culprit.

I think the cam only support 24 or 30 fps, so I suspect some sort of timing discrepancy as the root cause.

**Comment by ojack** [comment]
@echophon how interesting. What is the very first error that appears before all the regl errors?

Do both of these examples work with your camera+screen configuration?: https://webrtc.github.io/samples/src/content/getusermedia/gum/  https://webrtc.github.io/samples/src/content/getusermedia/canvas/

**Comment by ojack** [comment]
@echophon any updates on this?

**Comment by ojack** [comment]
@echophon i found an error and updated hydra-synth, the browser, and atom verion....any difference?

**Comment by ojack** [comment]
yay! i am going to close the issue then!

thats interesting because i dont think o0.scale would have ever worked ... or maybe im forgetting something
