### ISSUE TITLE
WebGL error when screen sharing Chrome tab

### ISSUE THREAD

**Issue by dundass** [ojack/hydra#29]
hi !

i get this error:
`Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.`
when trying to use the screen sharing extension to pull a Chrome tab into hydra using
`s0.initScreen()`
`src(s0).out()`
locally or using the remote hydra URL.

update: this also happens immediately when trying to use screen sharing extension with VLC (application window).

here is what the console says when it crashes:
`[.WebGL-000000C82EF494A0]GL ERROR :GL_INVALID_VALUE : glCopySubTextureCHROMIUM: source texture bad dimensions.`
`WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`
`Error: (regl) context lost`

also i've been on the WebRTC examples, particularly for testing getUserMedia, and it comes back with a NotFoundError. could this be the problem ? how can it be fixed ?

i'm on Chrome 69, windows 8.1. thx !

**Comment by ojack** [comment]
Hmm I am not sure, but it is very likely related to the WebRTC errors. Which examples have you tried?

**Comment by ojack** [comment]
Sometimes on windows there is an issue where only one application can access a camera or device at a time. I am not sure how/whether this affects screensharing.. but maybe could solve the WebRTC issues.

**Comment by dundass** [comment]
hey ! i tried the ones at https://github.com/ojack/hydra/issues/24, and they are now working but the screen sharing still drops out after running the 2 lines above

when u go to the 'share your screen' menu as part of the extension, the vlc window is shown as a black screen rather than the playing video buffer, not sure if that helps. also my laptop has dual video cards, an nvidia and the intel integrated, could they be getting in the way / conflicting ?

**Comment by TheWispy** [comment]
I've had an issue with the screen capture extension not capturing applications before. Updating my graphics drivers **seemed** to fix it, but it may have just been acting weird. It would seem weird that your video devices would conflict as such, but there are probably BIOS settings that allow you to configure whether integrated graphics should take priority.

**Comment by dundass** [comment]
thanks for the replies - @ojack it seems to work with a chrome tab fine, but with another application it comes up with a black screen surrounded by the VLC UI. weirdly despite that example working with a tab, hydra still cuts the feed off. also worth noting is that u were right about one source at a time, cuz if i bring VLC into focus with the webrtc tab in the background, it streams fine.

@TheWispy i will try to update the nvidia (& intel?) drivers

**Comment by dundass** [comment]
tried updating nvidia drivers but nothing's changed. not sure what to try now, do you have any more suggestions ?

i dont want to find another tool that allows video input because they simply won't be as good as hydra

**Comment by ojack** [comment]
@dundass i found an error in the way textures were being imported and updated the repo....let me know if anything has changed!

**Comment by dundass** [comment]
![hydraaaaaa](https://user-images.githubusercontent.com/25623031/48029949-77954900-e147-11e8-93cb-f9be45864ab3.png)
thank u thank u thank u !
