### ISSUE TITLE
Why are external canvases being aliased?

### ISSUE THREAD

**Issue by jarmitage** [ojack/hydra#33]
Some downsampling / aliasing seems to occur when passing a video or canvas into Hydra, e.g.:

https://github.com/ojack/hydra-examples/blob/master/5-video.js#L9

https://github.com/ojack/hydra-examples/blob/master/6-p5.js#L52

<img width="922" alt="screenshot 2019-01-03 at 15 33 16" src="https://user-images.githubusercontent.com/2885827/50661556-65932380-0f9b-11e9-9f2d-e6968225841f.png">

**Comment by jarmitage** [comment]
If you want higher res textures you need to override these:
https://github.com/ojack/hydra-synth/blob/master/example/src/canvas.js
https://github.com/ojack/hydra/blob/master/hydra-server/app/src/canvas.js

**Comment by ojack** [comment]
Got rid of default resolution so this should be fixed!
