### ISSUE TITLE
The active tab in Atom overwrites the animation

### ISSUE THREAD

**Issue by b1tdreamer** [ojack/hydra#34]
In the latest version of hydra for Atom, the active tab always remains the background color of the theme. Could it also be part of the animation?

Thanks

**Comment by zachkrall** [comment]
Hi @b1tdreamer,
I submitted a pull request to update the stylesheet for when Hydra is enabled in Atom. In the meantime, you can add the following CSS to your Atom stylesheet. 
A guide on how to access your Atom stylesheet can be found here: https://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks
```
body.hydra-enabled{
   li.texteditor.tab{
      background: rgba(0, 0, 0, 0.0)!important;
    }
}
```

**Comment by ojack** [comment]
yayy, thank you zach!
