### ISSUE TITLE
Feature Request: Add Midimapping for Numbers

### ISSUE THREAD

**Issue by dschiller** [ojack/hydra#37]
1 - Select the Number you wanna control via MIDI Controller and rightclick it
2 - In Contextmenu select ``Learn MIDI CC``
3 - Click ``Find`` Button and move / use your MIDI Controller Fader / Knob / Button / TRS; Enter your Min and Max Values for this ``Field`` / Number; Click ``OK`` Button

Expected Result:
If one now use the Knob on the CSX MIDI Controller with CC Value 12 one now can control the second ``modulateRotate`` Parameter from -12 to 1.7 by moving / rotating / pressing / plugging the MIDI Controller Fader / Knob / Button / TRS.

![image](https://user-images.githubusercontent.com/3144986/53291976-f3310980-37bb-11e9-8823-3883420f9b5c.png)

Or you could implement it programatically:

![image](https://user-images.githubusercontent.com/3144986/53292138-76535f00-37be-11e9-9caf-fda3833d4dc4.png)

**Comment by ojack** [comment]
@dschiller could you go into more detail about how the programmatic version is different from the webMidi example in the docs provided by @echophon ?

Is this something you are interested in working on?

**Comment by dschiller** [comment]
@ojack Hey Olivia, didn't know about the Implementation from hydra/docs/midi.md. But that's exactly what I am looking for. The only Difference to my Version is that you can control the from- and to-Values what makes sence in my Opinion. For sure you can have the same Behaviour in Vancy's ( @echophon  ) Script but with more Effort.

Yes I am interested in creating such FUnctionality. Are there any Notes how to extend the hydra Framework ?

**Comment by ojack** [comment]
I think I would rather let users create this mapping in a way that works for them. It would be nice to have a predefined way to run certain scripts on startup. Eventually I would like to make it easy to create user plugins and import them ant the beginning.
