### ISSUE TITLE
Discoverability issue on tweet sharing

### ISSUE THREAD

**Issue by mcscope** [ojack/hydra#42]
When I saw you present this, you showed that you could tweet a finished product and save it to a gallery and link other people too it from hydra-editor. However I forgot the keyboard command and I can't find it documented anywhere.

**Comment by mcscope** [comment]
I don't see a 'share' button, maybe that's the problem.
![image](https://user-images.githubusercontent.com/3921648/54944262-582d6b80-4ef0-11e9-810c-7e6a6d750eca.png)

**Comment by mcscope** [comment]
Discovered the issue - it's because I came from a shared sketch, the button to share it again was missing.

**Comment by ojack** [comment]
No, it's an outdated link --- use https://hydra-editor.glitch.me/
I need to update the repo!
