### ISSUE TITLE
Negative blend values give black screen

### ISSUE THREAD

**Issue by mcscope** [ojack/hydra#45]
Negative blend values work for some time, but then show a black screen, seems to indicate an error that crashes rendering

Try the following pattern in Hydra editor.  After a few seconds, comment in the negative blend value.  The colors should bleach (in a cool effect!) and then the entire render goes black.  If you comment it back in, the image comes back and is complex, which makes me suspect that there was a rendering error 
```// by Lady Red

osc(100, 0.01, 1.4)
	.rotate(0, 0.1)
	.mult(osc(10, 0.2)
          .modulateKaleid(
             voronoi(3))
         )          
	.color(2.83,0.91,0.39)
  .out(o0)


src(o1)
    .blend(o0, () => 0.01)
  //.blend(o0, () => -0.02)


  .out(o1)

render(o1)

osc(10).kaleid(6).luma(0.9).out(o2)```

**Comment by ojack** [comment]
No error is thrown but it has to with blend arithmetic... what would be expected behavior?

**Comment by ojack** [comment]
Going to close for now because I don't think this is a bug / not sure what should happen :)
