### ISSUE TITLE
text()

### ISSUE THREAD

**Issue by redraw** [ojack/hydra#49]
Would be possible/useful/interesting to add text as source? i.e

`text('wave').modulate(osc(10)).out()`

Not sure how painful is to implement text/fonts in a shader, or if `regl` provides a simple way to achieve that. Anyhow, super project

**Comment by ojack** [comment]
yeaa this could be fun! i think the easiest would be to implement it as a canvas source. this would be interesting to apply to images, videos, etc as well but I think requires a different kind of function/source than is currently implemented

**Comment by redraw** [comment]
right :) I was about to close this issue because maybe that's possible using p5 i.e
```
p = new P5()
...
s1.init({src: p.canvas})
```
however it would be handy to have something function to add a simple video/image/text

**Comment by JayMaster** [comment]
I'm quite new to this whole topic, but I would like to use some text. Can you maybe give further details on how exactly it would work with p5?

**Comment by esnho** [comment]
Can this technique be a valid path to follow for text rendering?

Intro
https://webglfundamentals.org/webgl/lessons/webgl-text-canvas2d.html

Serious stuff
https://webglfundamentals.org/webgl/lessons/webgl-text-texture.html

**Comment by ojack** [comment]
I am going to close this because it is outside the scope of hydra. For documentation of p5 in hydra, see: https://github.com/ojack/hydra-examples/blob/master/6-p5.js

And see the p5 documentation for how to use text.

**Comment by Sohalt** [comment]
Hi! Thanks so much for hydra!
Would you be willing to reconsider adding this, @ojack? The p5js workaround is ok, but I still feel there's extra value in a super simple text source.

**Comment by geikha** [comment]
Hi @Sohalt try the hydra-text extension, it's kind of unstable after long time of using it so make sure you save your stuff!

https://github.com/geikha/hyper-hydra#hydra-text

[example](https://hydra.ojack.xyz/?code=YXdhaXQlMjBsb2FkU2NyaXB0KCUyMmh0dHBzJTNBJTJGJTJGaHlwZXItaHlkcmEuZ2xpdGNoLm1lJTJGaHlkcmEtdGV4dC5qcyUyMiklMEElMEFoeWRyYVRleHQuZm9udCUyMCUzRCUyMCUyMnNlcmlmJTIyJTBBaHlkcmFUZXh0LmxpbmVXaWR0aCUyMCUzRCUyMCUyMjIlMjUlMjIlMEFzdHIlMjAlM0QlMjAlMjIlMjBoeWRyYV8hJTIwJTIyJTBBc29saWQoMSUyQy4yKSUwQSUwOS5ibGVuZChzcmMobzApLnNjYWxlKDEuMDIpLmNvbG9yYW1hKC4wMikpJTBBJTA5LmxheWVyKHRleHQoc3RyKSklMEElMDkuZGlmZihzdHJva2VUZXh0KHN0cikubW9kdWxhdGVTY2FsZShub2lzZSgxJTJDMSklMkMlMjAuNCkpJTBBJTA5Lm91dCgp)
