### ISSUE TITLE
using math. (lowercase) as opposed to Math. is freezing Hydra

### ISSUE THREAD

**Issue by rfpuyana** [ojack/hydra#51]
There's something about this sine function freezing Hydra and not showing any error. Hydra web needs to be reloaded in the browser.

This chain works well
```
osc(10,0.1)
  .thresh(0.1).scale(3)
.out()
```

This one freezes Hydra. No error messages
```
osc(10,0.1)
  .thresh(0.1).scale(()=>math.sin(time))
.out()
```
OS:Mac OSX  - High Sierra
Browser: Chrome Version 75.0.3770.100 (Official Build) (64-bit) 
Hydra: Web

**Comment by zachkrall** [comment]
Hi @rfpuyana 
I think the error might be because math isn't capitalized in your code. The name of the math object in javascript is capitalized: `Math`. ([Source: MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sin))

Try the following code:
```
osc(10,0.1)
  .thresh(0.1).scale(()=>Math.sin(time))
.out()
```

**Comment by rfpuyana** [comment]
Zach you are correct. My Bad.
It's now working.

However, Hydra shouldn't freeze.
An error message should notify about this particular case.

**Comment by zachkrall** [comment]
Maybe a solution is allowing `sin` to be a globally accessible function to prevent calling `Math` object directly.

Example ([hydra-editor](https://hydra-editor.glitch.me/?sketch_id=R3zRnjpjaXRNWQOQ&code=JTJGJTJGJTIwWmFjaCUyMEtyYWxsJTIwKGdpdGh1Yi5jb20lMkZ6YWNoa3JhbGwpJTBBJTJGJTJGJTIwRmVhdHVyZSUyMGlkZWElMjAuLi4lMjBzaW4lMjBhcyUyMGElMjBnbG9iYWwlMjBmdW5jdGlvbi4lMEElMEFzaW4lMjAlM0QlMjAoeCklMjAlM0QlM0UlMjBNYXRoLnNpbih4KSUzQiUwQSUwQXNoYXBlKDMpJTBBLnNjYWxlKCUwQSUyMCUyMCgpJTNEJTNFc2luKHRpbWUpJTBBKS5vdXQoKSUzQg==))
```js
sin = (x) => Math.sin(x);

shape(3)
.scale(
    ()=>sin(time)
).out();
```

Ideally, it wouldn't require an anonymous function to pass the value but I am not sure how that could be accomplished. Maybe @ojack @rumblesan @echophon @brucelane have ideas on that?
Example:
```js
shape(3)
.scale(
    sin(time)
).out();
```

**Comment by rumblesan** [comment]
so there's a couple of immediate solutions I guess.
* make all the functions/values on `Math` globally available
* create a `math` variable that is just `Math` so casing doesn't make any difference.
Both are fine, though the bigger issue really is that the undefined variable crashes everything. I think a better fix would be to catch the error and handle it gracefully with a warning so users can fix the casing.

I've not had a look at the hydra code for a while now, but I've not got anything else happening with my Friday night so I'll start digging 😂

**Comment by zachkrall** [comment]
setting `sin( )` matches how p5.js [(source code)](https://github.com/processing/p5.js/blob/master/src/math/trigonometry.js#L188) has approached this too

**Comment by rumblesan** [comment]
right, think I've figured out what's going on and opened that PR, but not had a chance to fully check. will get back to it a bit later when I have a moment

**Comment by ojack** [comment]
@rumblesan's commit fixed the function crashing issue, yay! And also fixes https://github.com/ojack/hydra/issues/35

As far as globally defining certain functions as @zachkrall mentions, that is part of a much larger conversation at https://github.com/ojack/hydra/issues/8 so let's continue it there.

Opened a new issue about providing user log info about what happens in hydra synth at: https://github.com/ojack/hydra/issues/53

**Comment by rumblesan** [comment]
hah, glad to be of use :D
