### ISSUE TITLE
Desktop Capture randomly stopped working both in Atom and Safari

### ISSUE THREAD

**Issue by xenwan** [ojack/hydra#84]
Apparently for no reason, Desktop Capture stopped working

s0.initScreen()
src(s0).out()

renders a black screen.

I'm running orca in Atom 1.45.0 with atom-hydra 0.2.14 on MacOS 10.15.3

**Comment by zachkrall** [comment]
are you running in full screen mode? i've noticed that in full screen mode `initScreen` needs an integer like `0` or `1` to identify which window to capture in macOS

**Comment by ojack** [comment]
In atom, you have to run desktop capture with a number corresponding to which window you would like to capture.
```
s0.initScreen(0)
```
It should not work in Safari, but in Chrome it should work with
```
s0.initScreen()
```
as long as you have the screen capture extension installed. Please report back if this works!

**Comment by xenwan** [comment]
> In atom, you have to run desktop capture with a number corresponding to which window you would like to capture.
> 
> ```
> s0.initScreen(0)
> ```
> 
> It should not work in Safari, but in Chrome it should work with
> 
> ```
> s0.initScreen()
> ```
> 
> as long as you have the screen capture extension installed. Please report back if this works!

It works! I swear I've used it before without the number in Atom. My old patches don't use it and stopped working. So strange. Thanks!!

**Comment by ojack** [comment]
yay! going to close : )
