### ISSUE TITLE
Connecting to remote streams

### ISSUE THREAD

**Issue by mariawitek** [ojack/hydra#85]
Hi,

First, thanks for developing such an awesome tool! 

I'm having problems connecting to remote streams in Hydra. Changing the tab name in the first window seems to work fine, but when I then try to connect using s0.initStream()  in the second window, I don't see the remote stream and get the following error in the console (see attached screenshot). Any ideas what's going on here? 
![hydra_error](https://user-images.githubusercontent.com/33524867/79065554-2331b980-7ca9-11ea-8574-c044e8ab4efa.jpeg)

**Comment by ojack** [comment]
Hi @mariawitek that part is currently broken in most browsers unfortunately. Working on fixing it!

**Comment by mariawitek** [comment]
Ok, thanks for the update @ojack !

**Comment by sanotronics** [comment]
I have the same issue.

Not JS expert at all, but maybe this helps?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject

**Comment by sanotronics** [comment]
I just tried on a local server replacing line 61 on https://github.com/ojack/hydra/blob/1985574d65dacea079bad1824b06090b7187de90/hydra-server/app/src/pb-live.js#L61

for the following 

`if ('srcObject' in video) {
      video.srcObject = stream
    } else {
      // Avoid using this in new browsers, as it is going away.
      video.src = window.URL.createObjectURL(stream)
    }`

And it worked, streaming to a browser instance... Once haha

Rolled back to confirm that had done the trick, but then I couldn't get it to work once more :/

**Comment by sanotronics** [comment]
Ok yea, it did the trick!

I just added that very code in the bundle.js file and commented line 1123 (same as line 61 in the pb file) and I got in Brave browser a stream from one local instance to another :) 

It's a really easy fix luckily :)

**Comment by ojack** [comment]
Hey I just updated this! I thought it was something much more complicated, thanks @sanotronics . @mariawitek try and report back if it works!

Closing this for now, but feel free to keep commenting.

**Comment by mariawitek** [comment]
Hm, I just tried this in both firefox and chrome, and still doesn't work..

**Comment by mariawitek** [comment]
Hey thanks @ojack! I just tried in firefox and chrome, and it worked in both! (PS: I deleted a comment I just posted where I said it didn't work. I just needed to wait a bit!)

**Comment by ojack** [comment]
Oh thats great to hear! I would love to hear more about how you end up using this feature. It was something that was initially a part of hydra (and was one of the reasons I made it). But since then I haven't used it very much.

Going to close this issue but feel free to continue to add comments here.

**Comment by mariawitek** [comment]
So actually I'm using it for maybe a slightly unusual (and less interesting) reason.. I've been doing some live-streams with a DJ and don't have a webcam. We wanted to use one laptop as the webcam (placed so that both the DJ and I were visible), and then connect to another laptop to make patterns with the output in hydra and send that out via obs (hope that makes sense!)

**Comment by sanotronics** [comment]
Oh I'm so glad I could help out!

I think it's a great feature to use remote cam like a smart phone :) this gives you a lot more flexibility and resolution than the laptop webcam

I was able to use initCam() to use the front camera and initCam(1) for the back camera. 

Will test later if the stream works but I have a feeling it will

**Comment by ojack** [comment]
Oooh this all makes sense. In the beginning I made a page that you could
load and select a camera in order to send a stream into hydra, without
having to load a full hydra instance. It seems like that would be helpful
for both of these use cases. Thanks for both of your input!!

**Comment by sanotronics** [comment]
I also have a friend who uses the output that [this project](https://www.instagram.com/p/B_DcreTpTUO/) generates, which is a controlled PWM RGB LED using the rolling shutter of the smartphones cams, and inputs this to hydra.

The result is amazing quite awesome :)
![hydra-RSD](https://user-images.githubusercontent.com/4588575/80392645-ced03180-8885-11ea-86d1-b24f7cd97a9a.jpg)

**Comment by sanotronics** [comment]
@ojack do you still have that website to load the camera? 

Looks like hydra doesn't load properly on iOS :(

![hydra-iOS-fail](https://user-images.githubusercontent.com/4588575/80399452-95042880-888f-11ea-9c37-2d4e5fc17a54.jpg)

**Comment by ojack** [comment]
@sanotronics no I don't. And oh no, did this update that was supposed to make it run on IOS, https://github.com/ojack/hydra/blob/5e289dc539ba51797f79e0d3840ba5441fb0e3a8/hydra-server/app/index.js#L23
but it seems it still isn't working. I don't have an ios device so can't test.

**Comment by sanotronics** [comment]
me neither, but I can work remotely with my father or this friend of mine to debug, if need be
