### ISSUE TITLE
Ableton/ csound with Hydra 

### ISSUE THREAD

**Issue by toucanman1** [ojack/hydra#92]
Hello-

Would anyone have a script for hydra that would allow me to retrieve csound and ableton OSC messages. I understand that csound can transmit OSC events. 

Best
Zach

**Comment by brucelane** [comment]
Hydra in Electron can manage OSC

**Comment by toucanman1** [comment]
Is electron a plugin?

**Comment by ojack** [comment]
Hi @toucanman1, you can read more here about using hydra in atom: https://github.com/ojack/hydra-examples

Closing this but feel free to continue discussing.
